In [3]:
import cv2
import numpy as np
import os

from PIL import Image
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D, BatchNormalization,Conv1D,MaxPooling1D
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import backend as K
from keras.optimizers import Adam,Adagrad
from tensorflow.keras.models import load_model
import numpy as np
import cvlib as cv


Using TensorFlow backend.


In [74]:
dataset = []
labels = []
imgpath = 'D:\GenderDetection\faces'
for path, _, files in os.walk(imgpath):
    for file in files:
        image = cv2.imread(path + '\\' + file)
        image = cv2.resize(image, (50, 50))
        image = image.astype('float32')
        image /= 255.0
        dataset.append(image)
 
        label = path.split(os.path.sep)[-1]     #D:\GenderDetection\man\face_12.jpg
        if label=="man":
            label=0
            print(label)
        else:
            label =1
            print(label)
            
        labels.append(label)
        

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


In [75]:
len(labels)

2306

In [76]:
len(dataset)

2306

In [77]:
labels = np.array(labels)
dataset = np.array(dataset)


In [78]:
labels

array([0, 0, 0, ..., 1, 1, 1])

In [80]:
(trainX, testX, trainY, testY) = train_test_split(dataset, labels, test_size=0.3,random_state=50)

In [81]:
trainY

array([0, 0, 0, ..., 1, 1, 1])

In [83]:
trainY = to_categorical(trainY, num_classes=2)
testY = to_categorical(testY, num_classes=2)

In [84]:
trainY

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [64]:
datagen = ImageDataGenerator(rotation_range=25, width_shift_range=0.1,
                         height_shift_range=0.1, shear_range=0.2, zoom_range=0.2,
                         horizontal_flip=True, fill_mode="nearest")

In [65]:
INIT_LR = 1e-3
epochs=100
optim = Adam(lr=INIT_LR, decay=INIT_LR / epochs)

In [66]:
model = Sequential()
model.add(Convolution2D(32, (3,3), padding="same", input_shape=(50,50,3)))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=-1))
model.add(MaxPooling2D(pool_size=(3,3)))
model.add(Dropout(0.25))

model.add(Convolution2D(64, (3,3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=-1))

model.add(Convolution2D(64, (3,3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=-1))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Convolution2D(128, (3,3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=-1))

model.add(Convolution2D(128, (3,3), padding="same"))
model.add(Activation("relu"))
model.add(BatchNormalization(axis=-1))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(1024))
model.add(Activation("relu"))
model.add(BatchNormalization())
model.add(Dropout(0.5))

model.add(Dense(2))
model.add(Activation("sigmoid"))



model.compile(loss='categorical_crossentropy', optimizer=optim, metrics=['accuracy'])

history = model.fit_generator(datagen.flow(trainX, trainY, batch_size=60),
                        validation_data=(testX,testY),
                        steps_per_epoch=len(trainX) // 60,
                        epochs=epochs, verbose=2)

model.save('D:\\GenderDetection\\gender_detection.model')


Epoch 1/100
 - 17s - loss: 0.7426 - accuracy: 0.6589 - val_loss: 0.7023 - val_accuracy: 0.4827
Epoch 2/100
 - 17s - loss: 0.6106 - accuracy: 0.7310 - val_loss: 0.6942 - val_accuracy: 0.4899
Epoch 3/100
 - 17s - loss: 0.5369 - accuracy: 0.7819 - val_loss: 0.7182 - val_accuracy: 0.4841
Epoch 4/100
 - 17s - loss: 0.4489 - accuracy: 0.8076 - val_loss: 0.6942 - val_accuracy: 0.4827
Epoch 5/100
 - 16s - loss: 0.4214 - accuracy: 0.8172 - val_loss: 0.6811 - val_accuracy: 0.4928
Epoch 6/100
 - 16s - loss: 0.3932 - accuracy: 0.8301 - val_loss: 0.8450 - val_accuracy: 0.4827
Epoch 7/100
 - 18s - loss: 0.3908 - accuracy: 0.8404 - val_loss: 0.6589 - val_accuracy: 0.5159
Epoch 8/100
 - 17s - loss: 0.3648 - accuracy: 0.8417 - val_loss: 0.7233 - val_accuracy: 0.4884
Epoch 9/100
 - 16s - loss: 0.3865 - accuracy: 0.8404 - val_loss: 0.5809 - val_accuracy: 0.7370
Epoch 10/100
 - 15s - loss: 0.3410 - accuracy: 0.8764 - val_loss: 0.4391 - val_accuracy: 0.8150
Epoch 11/100
 - 16s - loss: 0.3226 - accuracy: 0.

Epoch 87/100
 - 17s - loss: 0.0886 - accuracy: 0.9698 - val_loss: 0.1610 - val_accuracy: 0.9566
Epoch 88/100
 - 16s - loss: 0.0812 - accuracy: 0.9710 - val_loss: 0.1909 - val_accuracy: 0.9408
Epoch 89/100
 - 17s - loss: 0.0882 - accuracy: 0.9718 - val_loss: 0.1153 - val_accuracy: 0.9639
Epoch 90/100
 - 16s - loss: 0.0685 - accuracy: 0.9748 - val_loss: 0.2312 - val_accuracy: 0.9364
Epoch 91/100
 - 16s - loss: 0.0882 - accuracy: 0.9678 - val_loss: 0.1319 - val_accuracy: 0.9595
Epoch 92/100
 - 16s - loss: 0.0927 - accuracy: 0.9647 - val_loss: 0.4591 - val_accuracy: 0.8526
Epoch 93/100
 - 19s - loss: 0.0623 - accuracy: 0.9794 - val_loss: 0.1206 - val_accuracy: 0.9624
Epoch 94/100
 - 20s - loss: 0.0890 - accuracy: 0.9691 - val_loss: 0.2967 - val_accuracy: 0.9032
Epoch 95/100
 - 21s - loss: 0.0757 - accuracy: 0.9716 - val_loss: 0.1412 - val_accuracy: 0.9595
Epoch 96/100
 - 19s - loss: 0.0764 - accuracy: 0.9717 - val_loss: 0.2717 - val_accuracy: 0.9220
Epoch 97/100
 - 18s - loss: 0.0637 - acc